#!/bin/sh

. /lib/antifilter/antifilter.sh

help() {
	cat <<EOF
Syntax: antifilter [command]
Available commands:
	start                        Start antifilter daemon and load ipsets
	stop                         Stop antifilter daemon
	restart                      Restart antifilter daemon
	add <ipset> <host or ip>     Add new entries to the ipset
	delete <ipset> <host or ip>  Remove entries from the ipset
	drop                         Remove all ipsets
	update <ipset>               Update single or all ipsets
	lookup <host or ip>          Lookup entry in loaded ipsets
	status                       List loaded ipsets
	dump                         Dump loaded ipsets
EOF
}

start() {
	/etc/init.d/antifilter start
}

stop() {
	/etc/init.d/antifilter stop
}

restart() {
	/etc/init.d/antifilter restart
}

status() {
	antifilter_status
}

add() {
	antifilter_add "$@"
}

remove() {
	antifilter_remove "$@"
}

drop() {
	stop
	antifilter_drop
}

update() {
	antifilter_update "$@"
	echo
	antifilter_status_ipsets
}

lookup() {
	antifilter_lookup "$@"
}

dump() {
	antifilter_dump
}

case "$1" in
	start|stop|restart|run|remove|update|lookup|status|dump|add|remove)
		"$@"
	;;
	--daemon)
		antifilter_daemon
	;;
	*)
		help
	;;
esac

exit 0
