#!/bin/sh

. /usr/lib/antifilter/antifilter.sh

help() {
	cat <<EOF
usage: antifilter [options] sub-command

Available commands:
	start                        Start antifilter daemon
	stop                         Stop antifilter daemon
	restart                      Restart antifilter daemon
	add <ipset> <host or ip>     Add new entries to the ipset
	delete <ipset> <host or ip>  Remove entries from the ipset
	lookup <host or ip>          Lookup entry in loaded ipsets
	update <ipset>               Update single or all ipsets
	unload <ipset>               Unload single or all ipsets
	dump <ipset>                 Dump single or all ipsets
	status                       List loaded ipsets

Available options:
	-f | --force-cache           Force update of local cache
EOF
}

start() {
	/etc/init.d/antifilter start
}

stop() {
	/etc/init.d/antifilter stop
}

restart() {
	/etc/init.d/antifilter restart
}

add() {
	antifilter_add "$@"
}

delete() {
	antifilter_delete "$@"
}

lookup() {
	antifilter_lookup "$@"
}

update() {
	antifilter_update "$@"
}

unload() {
	antifilter_unload "$@"
}

dump() {
	antifilter_dump "$@"
}

status() {
	antifilter_status
}

while [ $# -gt 0 ]; do

	case "$1" in
		-f|--force-cache)
			[ ! -z "$OPTS" ] && OPTS="$OPTS "; OPTS="${OPTS}forcecache"
			shift
		;;
		start|stop|restart|add|delete|lookup|update|unload|dump|status)
			. /usr/lib/antifilter/palette.sh
			"$@"
			break
		;;
		*)
			help
			exit 1
		;;
	esac

done

exit 0
