#!/bin/sh /etc/rc.common

START=91
USE_PROCD=1
EXTRA_COMMANDS="status"
EXTRA_HELP="        status  Print antifilter status"

boot() {
	# handle mwan3 on boot
	start && [ -f /usr/sbin/mwan3 ] && /usr/sbin/mwan3 restart
}

start_service() {
	procd_open_instance
	procd_set_param command "/usr/sbin/antifilter" "--daemon"
	procd_set_param respawn
	procd_set_param user root
	procd_set_param pidfile /var/run/antifilter.pid
	procd_close_instance
}

status() {
	. /usr/lib/antifilter/antifilter.sh
	antifilter_status
}

clean_up() {
	# clean up spawned processes, e. g. sleep
	local cpids

	[ -f /var/run/antifilter.pid ] && {
		cpids=$(pgrep -P "$(cat /var/run/antifilter.pid)") >/dev/null

		for cpid in $cpids; do
			kill -TERM "$cpid" >/dev/null 2>&1
		done
	}
}

reload_service() {
	. /usr/lib/antifilter/antifilter.sh
	antifilter_update
}

stop_service() {
	clean_up
}
