name: OpenWRT feed
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Set up environment
      run: |
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list
        sudo rm /etc/apt/sources.list.d/microsoft-prod.list.save
        sudo apt-get -y update
        sudo apt-get -y install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
    - name: Prepare OpenWRT buildroot and feeds
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        cp feeds.conf.default feeds.conf
        echo src-git denpamusic https://github.com/denpamusic/openwrt-feed.git >> feeds.conf
        ./scripts/feeds update -a
        ./scripts/feeds install -a -p denpamusic
    - name: Create config
      run: |
        cd openwrt
        for PKG in $(ls ./package/feeds/denpamusic/); do
          echo CONFIG_PACKAGE_"$PKG"=m >> .config
        done
        make defconfig
    - name: Install toolchain
      run: |
        cd openwrt
        make -j$(nproc) tools/install
        make -j$(nproc) toolchain/install
    - name: Install key
      run: |
        cd openwrt
        echo "${USIGN_KEY}" > ./key-build
        echo "${USIGN_PUB}" > ./key-build.pub
      env:
        USIGN_KEY: ${{ secrets.USIGN_KEY }}
        USIGN_PUB: ${{ secrets.USIGN_PUB }}
    - name: Build packages
      run: |
        cd openwrt
        make package/system/usign/host/compile
        for PKG in $(ls ./package/feeds/denpamusic/); do
          IGNORE_ERRORS=1 make -j$(nproc) package/"$PKG"/compile
        done
        make package/index
    - name: Create repository
      run: |
        mkdir -p public/packages
        mkdir -p public/keys
        PKGROOT=$(find openwrt/bin -type d -name denpamusic)
        cp -r "$PKGROOT/"* public/packages
        cp ./openwrt/feeds/denpamusic/README.md ./public/
        cp ./openwrt/key-build.pub ./public/keys/$(./openwrt/staging_dir/host/bin/usign -F -s ./openwrt/key-build)
        echo "openwrt.denpa.pro" > ./public/CNAME
    - name: Deploy repository
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: public
        commit_message: Deploy repository
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_PAT }}
